# Generated by Django 4.2.1 on 2023-05-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rooms_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rommphoto',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
