# Generated by Django 4.2.1 on 2023-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_rommphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rommphoto',
            name='main_photo',
            field=models.BooleanField(default=False),
        ),
    ]
